---
- name: Deploy namespace
  import_tasks: namespace.yml

- name: Deploy configmap
  import_tasks: configmap.yml

- name: Deploy secrets
  import_tasks: secret.yml

- name: Deploy deployment
  import_tasks: deployment/deployment.yml

- name: Deploy script CronJobs
  import_tasks: deployment/script-cronjobs.yml
